<a href="https://colab.research.google.com/github/aristevski/playground/blob/master/Corona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Trying things out

Setting up Python libraries

In [1]:
import pandas as pd

In [16]:
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv'
cv = pd.read_csv(url, sep=',', header=0)

In [18]:
cv.head()

  iso_code      continent  ... life_expectancy human_development_index
0      ABW  North America  ...           76.29                     NaN
1      ABW  North America  ...           76.29                     NaN
2      ABW  North America  ...           76.29                     NaN
3      ABW  North America  ...           76.29                     NaN
4      ABW  North America  ...           76.29                     NaN

[5 rows x 49 columns]

In [19]:
cv.tail()

      iso_code continent  ... life_expectancy human_development_index
53525      NaN       NaN  ...             NaN                     NaN
53526      NaN       NaN  ...             NaN                     NaN
53527      NaN       NaN  ...             NaN                     NaN
53528      NaN       NaN  ...             NaN                     NaN
53529      NaN       NaN  ...             NaN                     NaN

[5 rows x 49 columns]